# Generated by Django 3.2.6 on 2021-11-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CasharkApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LastName',
            new_name='Last_Name',
        ),
    ]
