# Generated by Django 3.2.6 on 2021-11-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CasharkApp', '0002_auto_20211116_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Address_Province', models.CharField(max_length=50)),
                ('Address_City', models.CharField(max_length=50)),
                ('Address_Street', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('Bank_Info_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Bank', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Birthdate',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Credit_Score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Mobile_Number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Transaction_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Interest_Rate', models.IntegerField()),
                ('Date_Due', models.CharField(max_length=10)),
                ('Transaction_Date', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=50)),
                ('Borrower_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Borrower', to='CasharkApp.user')),
                ('Lender_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lender', to='CasharkApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Message_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Time_Sent', models.CharField(max_length=10)),
                ('Date_Sent', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=50)),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasharkApp.user')),
                ('Transaction_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasharkApp.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='GCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Number', models.CharField(max_length=50)),
                ('Balance', models.IntegerField()),
                ('Bank_Info_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasharkApp.bankinfo')),
            ],
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasharkApp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='Address_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CasharkApp.address'),
            preserve_default=False,
        ),
    ]
