# Generated by Django 3.2.6 on 2021-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasharkApp', '0004_auto_20211117_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Mobile_Number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
