# Generated by Django 3.2.6 on 2021-12-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasharkApp', '0006_auto_20211214_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Status',
            field=models.CharField(max_length=50),
        ),
    ]
