# Generated by Django 3.2.6 on 2021-12-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasharkApp', '0007_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Transaction_History_Status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
